
# Generates a release package of the plugin.
# I feel like there are better ways to do this. This is my first time doing that.

name: Make release package
on:
  workflow_dispatch:


jobs:
  build_linux:
    uses: Zylann/godot_fast_noise_2/.github/workflows/linux.yaml@main

  build_windows:
    uses: Zylann/godot_fast_noise_2/.github/workflows/windows.yaml@main

  dist:
    runs-on: "ubuntu-22.04"
    needs: [build_linux, build_windows]

    steps:
      # Clone our repo
      - uses: actions/checkout@v4

      # Get builds
      # Downloads all artifacts
      - uses: actions/download-artifact@v4
        with:
          pattern: libgdfastnoise2.*
          path: project/addons/zylann.fastnoise2/bin

      # download-artifact does not just download the file we want:
      # it also creates a folder of the same name, and then puts the contents in it.
      # So we have to fix that...
      # See https://github.com/actions/download-artifact/issues/141
      - name: "Fix downloaded artifacts"
        run: |
          cd project/addons/zylann.fastnoise2/bin

          mv libgdfastnoise2.linux.editor.x86_64.so temp
          mv temp/libgdfastnoise2.linux.editor.x86_64.so libgdfastnoise2.linux.editor.x86_64.so
          rm -d temp

          mv libgdfastnoise2.linux.template_release.x86_64.so temp
          mv temp/libgdfastnoise2.linux.template_release.x86_64.so libgdfastnoise2.linux.template_release.x86_64.so
          rm -d temp

          mv libgdfastnoise2.windows.editor.x86_64.dll temp
          mv temp/libgdfastnoise2.windows.editor.x86_64.dll libgdfastnoise2.windows.editor.x86_64.dll
          rm -d temp

          mv libgdfastnoise2.windows.template_release.x86_64.dll temp
          mv temp/libgdfastnoise2.windows.template_release.x86_64.dll libgdfastnoise2.windows.template_release.x86_64.dll
          rm -d temp

      # Get FastNoise2
      - name: "Get FastNoise2 for Linux"
        run: |
          curl -LO https://github.com/Auburn/FastNoise2/releases/download/v0.10.0-alpha/FastNoise2-v0.10.0-alpha-Linux64-GCC.zip
          unzip FastNoise2-v0.10.0-alpha-Linux64-GCC.zip -d FastNoise2_linux
          cp FastNoise2_linux/FastNoise2/lib/libFastNoise.so project/addons/zylann.fastnoise2/bin

      - name: "Get FastNoise2 for Windows"
        run: |
          curl -LO https://github.com/Auburn/FastNoise2/releases/download/v0.10.0-alpha/FastNoise2-v0.10.0-alpha-Win64-MSVC.zip
          unzip FastNoise2-v0.10.0-alpha-Win64-MSVC.zip -d FastNoise2_windows
          cp FastNoise2_windows/FastNoise2/bin/FastNoise.dll project/addons/zylann.fastnoise2/bin

      # Copy license
      - name: "Copy license"
        run: |
          cp LICENSE.md project/addons/zylann.fastnoise2

      # Remove unwanted files because upload-artifacts cannot filter files that go in the archive.
      # The goal is to get an archive that can be decompressed at the root of a Godot project, 
      # and have only necessary files go in matching directories. This is how the asset library works (otherwise the
      # user has to remember to manually choose the right path to the addons/ folder)
      - name: "Filter files"
        # Delete all files in `project/` except the `addons` folder
        run: |
          cd project
          find -maxdepth 1 -type f -delete
          ls -l

      # Make package
      - uses: actions/upload-artifact@v4
        with:
          name: GDFastNoise2
          path: project
